#!/bin/bash

### FLAGS ##############################
set -o noclobber # Avoid overlay files
set -o errexit   # Avoid cascading errors
set -o pipefail  # Unveils hidden failures
set -o nounset   # Exposes unset variables
set -o errtrace  # Trace error LINENO

trap 'echo Error at $LINENO' ERR

### PRE CHECKS #########################
if ! command -v pastel 2>&1 /dev/null; then
  echo "pastel not found."
  echo " ==> https://github.com/sharkdp/pastel#installation"
  exit 1
fi

### SOURCE #############################
_base_path=$(dirname "$(realpath "$0")")
for src in $_base_path/src/*.sh; do . "$src"; done

### START ##############################
main () {
  generate_seed ${1:-lch_hue}
  generate_palette
  generate_shade
  save
  demo
}

main $*

