#!/bin/bash

### FLAGS ##############################
set -o noclobber # Avoid overlay files
set -o errexit   # Avoid cascading errors
set -o pipefail  # Unveil hidden failures
set -o nounset   # Expose unset variables
set -o errtrace  # Trace error LINENO

trap 'echo Error at $LINENO' ERR

### PRE CHECKS #########################
if ! command -v pastel 2>&1 /dev/null; then
  echo "pastel not found."
  echo " ==> https://github.com/sharkdp/pastel#installation"
  exit 1
fi

if ! command -v bc 2>&1 /dev/null; then
  echo "bc not found."
  echo " ==> https://www.gnu.org/software/bc"
  exit 1
fi

### SOURCE #############################
BASE_PATH=$(dirname "$(realpath "$0")")
for src in $BASE_PATH/src/*.sh; do . "$src"; done

### START ##############################
main () {
  generate_seed ${1:-lch_hue}
  generate_palette
  generate_shade
  save
  demo
  apply_plugins
}

main $*

